name: instagram_clone_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0-210.3.beta <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.13.5
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
